apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-db
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  instances: 1
  inheritedMetadata:
    labels:
      workload: selfhosted
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          workload: selfhosted
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: tandoor
      owner: tandoor
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/tandoor-db
      endpointURL: http://192.168.3.20:3900
      s3Credentials:
        accessKeyId:
          name: cnpg-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup
          key: AWS_SECRET_ACCESS_KEY
        region:
          name: cnpg-backup
          key: AWS_REGION
      wal:
        compression: gzip
      data:
        compression: gzip