apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  namespace: media
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  resources:
    requests:
      cpu: 200m
      memory: 512Mi