---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: email-secret
  namespace: tools
spec:
  encryptedData:
    password: AgAwyTXusEGQ2y9Kkt31TSr9vl+ShPATmSyUlTOvpLp1l7eXejCkChw/hE+tKAoi0r+vzGXlojzCQzBSXGIEOYOIJetoBiU6DQN3EcfItKwce0sh5NXhgWbwIoIGWWeQgkKYlAau7QqA58UmXdpnZ2emwqmQix0VNtllKJYMGKoL5uVQ2GlYLhBEAadv21M8EQgZgeDOoOGhEnY7qoKNVimWRjdHVLc5ED1eLqfnxP7T72NHloV2LKRTs79XWSaBi5P6+OdqbI+n3OCizsQb6EqAf2Gqu8nkgm/zCx6xiugNBBvdmXfatFnxQlrE0hWijVqpUkE+nKt7n8LVfhZBmlypBjVUCimvSzVLYxTxuNCtO8rx+SJj4CB7nW/9DAgzG4cMzYhh4TFVf7StjPgo+x3ihFPdCwvU1rn++4W7f9IVBivgcXqmx6piD4rKweNkfOtCxk6k6IuMAa3zlqYUev2bqBTacN6XxbK7c50BZoviNxVuFlZ45d/cPded1oSdI18KLa8vHYfPnJoEXegWCClOersp1RPY55lobw3ANDnvtFPefHw+nRijrOOc4cB9Q/1BirRi5Rc+UoWCzLLSxRCJpuFPBZrfGLg6Sk1Bu6eEJH9yJhVjc3pqLoK2pHSnbrzU65mLsvxEeM6U5JLEPXyoD0CGRcUyOyhs2+29SNnjgi1Lbg/XIZNWnCc2g6VPWA5jFEoDGLmtPzuzyPjBy4NQ9Eiss4abVehp2ZDo
  template:
    metadata:
      name: email-secret
      namespace: tools
