---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: email-secret
  namespace: media
spec:
  encryptedData:
    password: AgBnA1warkKffeagxfGbQPMbcB+OBBUppR38yIPEdizS0xbrDFrMLQqEngOtqk5pQJc1fB6k7XAzpWpIIdLC16jgwBBFZOYtteAL9jcSzZwUfbwz7sXKeRJafjJ7G/XR2rokNYvB6rr4UR9G4A/1J/7TgpdsLElRZihr5AhXfEobENmMN7mvJi+V8zCDh6zWMr0ECvrTvUgrDsasrPMO1jTVNENc8YEOt4Kz6b2h/aTBbezARgctWILcoYwbNv1eyzcj8rwKpE1IR4BJXXbnK5k7Hpgxd07YRTbRTdK7mfPTQG/1CCC5znhShnFyB/FckFJPDwIb9imWmRmbW1rmrKChn7QoG5XEO/RWm8F2+cD6K/qli0ejtsWJgY00xq511WsSfgZ0iWpWSMM4i0kIqlBKHGsgYPU/EmhcutEysIRGeGXKBMm6SNCobSY9vbAD0Bcge+VjUcmV6UULdwzGvcrNCTwWCZuvc4/IedBcotTKhH63HstVb1dYYVURhwWNLq3XPG9hgAim3nMopv4yGAqF1fTdyEQ1mEbk91uj7x4eEMfEZZoWtdXOKUJfS4CXXIPAMZyo8ZEYB9Zzm5qyf/4oCnf79TYURmTMWr6SdTfqV7/749BbpwPtIqHXZs4eJaXuq1DLuQqj47Uoxrudea1B5ROHgjAB3LHtqT6ufWv9oEEaQYFm+f8HsJ8/xAICRSEYSE1uicZ0tDzCdmpFDMtJ7XEjbxtBEiVQTpGa
  template:
    metadata:
      name: email-secret
      namespace: media
