---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: floppy-secret
  namespace: media
spec:
  encryptedData:
    SECRET: AgCxnZRUHm6C3wcdiha9GeTDnuAe4DXQJ2x1g2YHMUzz4OOGTEC/IOVG5wpEFG6BV3JPlx6iC9pLrM9zibrvgTmBI2i5UqnlafS2sAG17I6AywkTA5g91sbdafNSHyAlNyMfYO6NSgmKA1K+4NK842RQCE2+pA5D87zcZi17dTViGS/TKpyKDKSbY8isBcnEw6vJL0zQeEPaPLk4UPKF9Lig1M513vaAJKRWIRRqtUy5lp2beCWIajnhROIDNNgXvaPbImYwH4O8YvwfNZIQiQp9pqH/y1sLO2HMLvQgkG9PnYFfVR7vlS1ntoNVOZzC8YJHLtyymNNcU83CQI/G01K8vnf8AJPYK0vvRHtGjFI4MlCi4jT2jF06ZXYUX89DhRPvC3YDsQW5lEz6qnCc/eMAwH35pRu1ad7uzh7Req0mAJuhHZi0R7vFTjtKK7UAzrGl8ud8+HCKEc+gUb51pnNx9lF4XZnA9ujU0oIneNYxdAveRmntOaTk6bRNpu7Lxs6J/8xi+tTVHNPXvHavltycWnYZ971lio7rA4QoBZuzDg4hjbXx6ZFIx4HCGwK7IObsaKahs9uIPwY/VcRmDO2lfY3BqrYvWb9G26TSnqlW4FSYmej/PscrmxeiTDuImkUOyFvwWomiBIORiEsqdHecV7buwWQqZzHw0bbRFHkByiXa2MFVGYi3/zAO5dniLt6+JvFL0gCsINz5P/qABgyxY3nNvm0yLEUmjNwZ9r8fFEc8+LIOhuQhxjsIJYbjWgDEP9hSWVZQUa8vCKlM8RQh
    TMDB_API: AgAjdcE3FBRVo6hoL5pYN3Qfg7YgBIlcD13QO+lf8BfHUyBGGZNOWAU7a7kNPhV0/4IZHgS7R2huhdN9reY6Kwy9vK3ndymHtUdX+kr8qXMv6qnfipnYYkXxJT6T4UHM1AS9JZA12TXCvrJ/99jO9PWXPYHlB5EhniFX9I8rS5sl8q1Ye0kDDm5VY/NpC9UiTuP+qOrm1/1RPKfLW5VuEFEvDOfuKoM94WsT+T3/r9kPedA3F0bUA+L8743XnuOY1R3Py4JwjAwoBqyf3zvzVVTp8D+LRKxfBbtHY8mcIkXbGsj88V4lRY8EtVgJpu8pcntrWiAOhw8oPi0qFbKdFZj+RQuacZc9AQGUbjmQZzcje1FslXe0Lv0EODuUtIzB0jlxSDA1A6S4V6nodpqNMP4k3z3cDpePuQ9ym5ogiwzaj/K143X4Pwwx2s3kOlvoieKgLfvPFHGEzuGCJAL1boCY1pbArwe/nnv76uVY2gUvKVffK0PkgVUv5qLIJWemh5eozUr3Dgi0KvdfoKfBoqKYYdce6fGhkBICE9H/1na5JE3Zk4IFRe+T5SAOhIdEpvZP6jhO6Yfjp84tu9O480ZyDcHBO3kQijDpSwsUjFgWpNGo0PHdCD6R28ei7S78Bz3kAGGJFEmCkaGztQf2hXwBEDO0lmSBgey6IDVDQgwyNPEOpjmOJ3R7FqzoLwV1uLxweCI9k3mi3vsmJ7rCXC7yTkmY3QATuUtcWV4ntPZt9Q==
  template:
    metadata:
      name: floppy-secret
      namespace: media
