---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-oidc
  namespace: media
spec:
  encryptedData:
    SOCIALACCOUNT_PROVIDERS: AgBDY6ImR5eAEgWjl/TiqIrooZtTRA0fJMYrmGv2fhN0Q3N5dOhRHVgAE2+sMTzwStReyL42jMsjq4JglSvu9batOsAIJofuSFDeyqhqCUT7/ZFmYQBq6tJ2MEVKgnsH/vq89v2EfH4TKs8A0RrSyekmeC4CogHffHMWYco7RLeoOiszYspNuohO5tg44TSvOdrLxq0GMh9aGIQsBEl0tGMtl0AmgWkleSL/LWl6GuDvRCfaGed7XIaYBUoEssTIcq00Avb3f2Ut6rjvJF8G1ZQb8YZ4z5FuBN/rut/Wu22PpSOfNKXfvplYhpL0dTZ6+EQigKQDvICCDkC1gsfUk9QvZmi9a942fsWUdFkJJlXteR8DbZLPMM1ifJ3Y3OC/D9Hc80+Fr4iQoazn/OAdZMDOdfbMyk52NUlstdeSNiaZsDeGcv0gNMLKeWsf+giffmc9b5PP0t+V8Wj37eAAGVHxjX22Jn441uJlKMxDPoxCUP9I0GnI494E+GbhQyOGfjzOXWRPYxQsltvPlNgtfaf85v5P2UCedtrfBEsPFqaQASm3M2L1vS5V7oX/wqs9QqEr45NcZJc6pCm3Y7kcGAFeZH9e8qBCf8tYYVhODoBwDg31dpicnRZrtrqKpuayvWRWcfjBLkz5j2t3mQgHe8d2EeTXdZsYIKs47tizLb1C3EL6oU9a9FERweXRPLK+Vbpn7Xc+S81BguAxVK5Q50V/zm7A7cCKzNzgkD8j+0WyXiaIiU56XWe/O97gjLFctmkWqVDbqnyBI5sHpJRkudk/YPxqdaJm23wdStNtxN0Efn1oSteNrxsCkBOY291RVMFThIY+IoGn94ziO3QlRKGFhD8lN/uNP5erb0AwvQbCS+Fuxuht27zKwny4KunJ0cyv818B79Kgp0Ng0aS3mJbks4pfXjkjyBUpxysz6sBxnjhSPm31CvPF3Av6mczLwMh8GF6LWjoob+8xR/wGp9yEgLTFaMD9s50WqOq36RxXbosqQJpDQ6/Byg/1W1qthpvJQ1P0ZnkmfdXLZZSrg9cn6QDMTKXW/aX942gP
  template:
    metadata:
      name: paperless-oidc
      namespace: media
