---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-oidc
  namespace: media
spec:
  encryptedData:
    SOCIALACCOUNT_PROVIDERS: AgAllOJKRTaxcVi73z7CJveGOz+3hRJWrQK+3MWBkCMeJSwcn8i8azbmr58xuEDdbZwmWN2NRnG0OQ3+psLJmvwIa2oUARSQoEQa5CmxQz83437tm/aNI2xQGKiOYw2PepnxkpzTd8XT2199u5vp1jcEDUXA4SzudpmmRvvchzAcJKA+yMUadz/rT2CtjzYiUzWMAjzct2v8ebpbOVTV9e5BBOUE3l7Nb3yFTkqXrw/sB/+YjA/RzvV9XEO3YOHjaWQhji/sbJ6CMNGb56bv+I7E+BRg+whUyHPfLHXc2gI3q8Fizg6sG1JNe+ngpGGiYbPsKbh8ePc5FjI1zlB9I+TSNk+7H7xSm8+QGu+0Byu2Pkw+wtOnjVEJUB/Gqa8H0blXka6kKaiPaVLHG82Y5bDEe+1B1W0cpPTLnJrxCm04sWRbsbEQ9875VWe61XQ8uHiby4/F92z2KQhOTnjxyBq9QR1wb4HC2I5hRAa8Z3j9FO176A8Izzuonmtiw0Hg75tkXEBSGtezWmjZrLpmC2ck1jSzewYBTSjdZf2zZyMLyRX2iwgqYKUXBB3rHz8Cd9sa9u12B8ojD53ojkmqiU1Urs2KIUCqJZjCLYTuOQW4smiH8FRWxz3Qt6VZRNCOCzw6IgJ09sriu8/Fd5CzpbSfRkxHAMYtGVVucVfZEKakM2tVwhIjI1EOPwtZm4Mc1auWQ5kF+gJPOX4mJjr1dYU/AedtaWqoDJe3pt5KLr92IoaLXdE9SXlHd9oagXgWnW2tMHlMDysIBY7371mpCccgfOGbIAesM4q3GuvIgSRtOat5RgJOAFd3Xi3QqnLGF3SJIdx7N38CIMqrNCAR4cEK6tblHmv41Z/MAGWIEaKxYChif8H4j5VWBxBfEK0CkIMkYpZ06OZnT0wrE16OcpOC9csQ3llJE6925rabpvYW5L0skUfUlLI0/UwEcDeVXDqGt1TUjNAXRlOg5eyRTq4uBH0avN6Deyh1jI5TAv+6R/Z2WCF8mR80yg91R1rMZqgN/EzddovB8LS7GZtrxw7cdm+GAEXuUSBnY3QNgfa0tVOsUuZCSYDMVjd8ALbIv0SlHcky2nYA
  template:
    metadata:
      name: paperless-oidc
      namespace: media
