---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pwpush-secret
  namespace: tools
spec:
  encryptedData:
    PWPUSH_MASTER_KEY: AgBgs/j+BHWNEp6r6TDmiclPDh/ql8Iue4f/4nXmKNXaLv73PZswRMqVVLiMqurMOOI9lc7y7OEu2o7G5urV3UdOrFZVRqCk+t5nYIqR+JicYqAAZDfC0yTzUGKJFg4DKn9pCaPT6cuktKLsKwwPAg6lgrSztm+9PC4YRWEOoVIxCqSixnW8navn6+QdOLjJ8Vn6Vonn6lZkWq0hxQSdd1fU9F882H4OnhOhQyAF0fASgFkl3C1qkIkjrMuP12dbXnowsCMrzF6wHTGYHPRG3vLhF5R5Vptwp9a+H9WAah1ogMdC2jdMi69oCAgbMHWA22pUL7JOdEgkC8KymFX3mIGfXj35D3lJ6NXECMfMfg6exABGNcU27sujGRC8mUtBlI44n2xVryx4THN9BdRRp0/1CLIM7C5aBUmleo7mtg4Spq3DdOBMLFMtC7wAld+Xfuox9/LOk+NZ+4reFcTkfMDDvsIdU5gkQwWLddltjYDgpMmctM39H8gvQz8xgqrVU1/9Gd46M320lGRdJ0Q4yrpmXbaVD4W6PbYfsLVk3IiSL/6302Fa2TzaiNti6KoMI8gMQLbVq1HG58vQarOG2nW3Sk2H+JpDIOZ92ddh3sXsd+YD1fENpbwQqi7tqVl07t51HwtPGjT5B5QWFAri1As/8rlLFHhnunWxE6vFf9s5etOZJ/uqEVQx6re+jCbQD8HMoNo9BjrtPZN6luisDJFNnlD0tipHyTPA4W6RYQUTHgXgZ41e12+xfr0CeZN3H/yrw6saaekJr5/5XmVYmis3
  template:
    metadata:
      name: pwpush-secret
      namespace: tools
