---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rackula-secret
  namespace: tools
spec:
  encryptedData:
    API_WRITE_TOKEN: AgCsHClFt8oI3ykUHIOlUgtnOYyLQHenzb8sic5p8zzWZ2sElsxne0MpRLacEU5vC1UlezeU1GkTwmI57pqBp0ADNCv1fV2LIpQD/uQky0Ydsak48hECXpDX57mf0itJWuhxQ89P8Qipl9eHpoW31r6qPVtAEf3Eo9sqvMANDC19Y9B3TzJ89OlzhET7o/uBOpsds2bdFRTdoW2Jwyk8MBceomTYJlnYY6u/Y5A+HQ3Xn7jdqkQuPw/XkAMHOHkz+d2RGNlGXQNMJwI4SmFIT7ZoeQ3Uejmakh90w/GcgUAM3oq7B1kwEFMRepUR3RkKOvCuMRVgKf5EuXngBBkEcV/Ia6DzaM9C6BW3KnpsHGLkfBFpNlFWZXfoxCa0IAGIwahx/Dy9My1AyH11waPd+dVWLsstj+YfUpab7MAyXap4qz+oVbWsDhymQHK2Gx3/Zbmz+rcRZKTuYUJQ9GoSU2BFzSHS5p8Nk2Y19ogARgbv99pNQvCrXlB0tWYZXlLtxOxOQrEnrXq4dZmN7Gqnpwxya0NgqJ4kWVM7O0RruaTImmQX8IvQOgRs3Y2ghKGrXOaNLQ68BnumwXcQFa2gJ5TyOEBuPRtogrJIwuql5n9OyXxSCDISCqZWhwLg/DdeCPqgrSdWXQp0RHXEtblxM6hC4Wi2D5UeRYHXN+O2sj8pjYXCSvym9BPyd3VvoAVEfkma/kzVCZTZZs2OeYGyngBitOhLe9cnbBwu/cZ+jMnT/PZCb7JFejlShCy/uKDblolzIqjUfKqlRjdVAm7ifFoH
  template:
    metadata:
      name: rackula-secret
      namespace: tools
