---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustmailer-secret
  namespace: tools
spec:
  encryptedData:
    BICHON_ENCRYPT_PASSWORD: AgAwOtv+vNkrP9D1hl7RzKGayBbqitjwlNOYfB8wE9WiMyP7tcZDHetHnVEsndsvbkRgmcG81c8xT5ng5vNBqGixwpVkvJS6y3r5NMWyil114TISUMMqm0aYboPNr+XqnAE2t47rlOJ1UjfM25T7nqWA1z3vEkCoze/JvzCbZmTMMWt07uIFnNkmFyoxNG88hXZxT5ottYEbwYnr7sIzWwygdVQg6DwLxqM7hL+ft5I34UVnmq/tup+X/nclsKWTfDSH1cnjSR56PDcihyC4l+dB/+cziWRh6oJXio64CCar81EknpRLl7Sd2jLUszwijvRS6dswN/49qa7iREUlTFsTorqCFJmQuYNxUFSNWEAPRPaM8iccF5zrEKJAeYiTaO1I8pafLGLG+YdLO58HjsmXL7oAnwP3SkKG0gBdFq1vNztECffa4fpeAc07xksDLibQtV0Pni38jKWzDmGm75wWUN6487R5r0S1clLbt2D5Gn17PkVCzTiLPdThOJAxVU9w9nI8ceEjmy079YZpMOP8jOTKIJ2BIQHtWdoPCHkCNvkwUj2cI+6f2Jkwn3zWcQ3WhG06XnpzX6yuLxnlBn6dSp9reF57c2VwJ19Gt53mpJyyluxProEpQHLR4/zVsnUhjddjuCOBq9BDzlLDEe29lWkDF5oteoJ5wjonkS7fqx0xmSGMenujflUibktiHh84hTd3jAFOrO92fjlrW+j53eQX3GYxTAJnaaPPpEBuTZfRo73ihrbxpymfLNCIaMM4yczGoVo4MMibfw9pJB1S
  template:
    metadata:
      name: rustmailer-secret
      namespace: tools
