---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tandoor-oidc
  namespace: tools
spec:
  encryptedData:
    SOCIALACCOUNT_PROVIDERS: AgBhiRW/3XqSgxZPclS7GgWyTvcFgBAMMFtSRFkLGJdCFzqxS9IghOIZsQie9cofJnR4JZmvIQryjv4hJPXEjNwqg3TBAMeUiKocik+qwXnHSeN8ykoSvX3Q8BiMekef48VVAHnC0mbjFWCsHE/h8pBDC4XmZr3/ZcsglQ4YwCcFuzCUXEYublr889ncwesTZXP5zVTccE68SMtUEzXA9zHGRrYa2L+R7k19RAmjIwxnqU0kLt0kiosaCAW1rVs6WPaMx8Pi1hEDeTt8gCaXDM8/1xn2xNseMuZAQG2cgmImZwHS9K6IfqhljZ8UC4gAqLtXg8QKdlPRGEH93d/IQ4FkND/J5a1IUJ4Bwoom02YYl94gO6crlx3fPKRH3+we1u/HP/oVz2vHPHT/aKCTeNn0Hu7QfwFN5UKSFNpdKHRR8mfcQ2/E2PIGJEFBOAWVYG9FaUur1PIsNZirGDal/dcYl5SpnNlX9DiB2izOqMjro9sVGN0rz7icsr1Hahx+ipBLworecUU42T3l0fJV2/6570uekUIjHscsyX45XdMzzHbKDgbcxEcBpWuNBBJhcpcWj8M6kNTb6JZ4F6CxfjAXeo2N/tvHLcOILXUgEtuTANFXKbpzQF1EcwCMyKfrwsVp8zFalJcy7HYQzMD9PlzifFqPkC/v2wyVJHAbxA+C8ntGuK0UvattliKjCWdLVAVhzlE6T4UtG55SPljtOgRN8Hz7SLjgobLb6VTe6XTLY6egOy+Cf2+TAvYui3UiPyhzJZdB8AP3h46H8j5DrhDsc9JKl0b4ZFMTtd5YdfNkbkvE20yujllQKOJt5HD7gtU16E9K/W0t1ItHG9JqrdI8dF/knss8MJB5ObkTXUOCj+HM31IjvvltGjbsfDDvayl4oM3hCDKVJbc8vuxJXLayQNzUqbjt4UOdrXTJmSU1RYU49kkszKG3RKDilSxMvY28R3th6qv5DOywKthzFq28JnyCg9rZsULCxXj5zwVCAMMunWtXrEuJvGyZIBpDdetpKoofp5ws1pfkxB6gU0nXtqSS551Yjp5u6V2SBIVtENhWRr5sR+7dUwwQWLRh/EBh
  template:
    metadata:
      name: tandoor-oidc
      namespace: tools
