---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tandoor-secret
  namespace: tools
spec:
  encryptedData:
    SECRET_KEY: AgA2Su/UPu5eXR7QGJ8JNqeo0pcKaaHFTdqPRW/aOImYvA0OE6QNJQSBoK5K8+S7s4MgMbL6WCgu7k32hoE/aI0Cw2gsV2hIqX2SWArEUuSiYkO+1yaNTzj7W4w6dJYE3cwFXRTcYlHH90LT29u+xO3uN0cRv1Y52egAJQFs/pp6mDbWYx5oDJG9tT2z3AswF7Ohhoeeqa1gW6hZD2TcqMiTmoGmTK6vWeP5biHVjE4LG2TIRpPzHWu2M/Hji6+1Bvf4taoLL3+MyH7xJp8iKUyZ2zzk4o5l73x/0TLLOsvodvWEzJCH3A/lnK28sR1c3Z5J3sYbqO4jh+9lk2lGUaJnFPxfEr2+mnfVesth2+/sdftRDVW9p87177+Y/sn8FpJEL2955Q/ZWnltFueflktzouaqqq8cSNoC7Qfk5K/ItKFYbNKX3C/KPBv/7r52iicz9rGDxs147cB+4OI/Y8PdQdjpkngJxoRVPjPVSH1jw3PsGKJGtusZVII9e0aitJ1VhNiSNUprRlMA45kBehcYvcs4spwv5L4+rK+Id3P0lviptNPd8Bk81cqPBmcU20or4bEsEbqJe3AA5Ryx0WYITb6OajkTzu3LIm13UgczVse4xpV087r/LnLPMA8D8wTFgk1UaO/jcnaYya9AJZ1Ghp8FjQlHhww32uTnAAWlxFwAMq5RMlWZ7swt1XWbRomfjRC6AXlHn6m1xshh9EzLZ0+N/ONdd7oC4HVBcjMB1WSv4h+VMb+ALNgw0k/Ejt+IpNNXdj4gpLlse0B0Q0VK
  template:
    metadata:
      name: tandoor-secret
      namespace: tools
