---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-oidc
  namespace: tools
spec:
  encryptedData:
    KARAKEEP: AgB2hl/3eGa5mwnXrQjILbmj6sOqWAkNrHSILhMOzJSFm68+y47TeXlloIFhO72sAxp1eUZmWGXYf74+k7+oW16d8VVhaJmr4ZhxYMeuN7ZKrssxbd3yhCdemhOWUiC0eY9ugP8logupbZjbvsCiKvsJ5HL1bvutcrkum9JI3zgbutlAZ3iNQN8rXeezuS4jtdGcXScskrSO2kJuUVWjbehtqdG0eWOv7r2lVCJM9RzwREXIuXKELxoD7kkzFN9EIyXRbWwb21YrVhva20icgOHfhU65EqGkzXFJR12dUK5OF4gBX030ps6SQlceFU4aHlPTKoY1UwzEak9HYBF2XaW8/b10jYRVPRasQG2Byb7InYoEUJoCZyMcHtZaAn/e2SPrdg2FmrfE74UbF0PSWW608oVepJ0EoOxW3IWQFH5caDVtMa2Gp1H84WV31f1y6N1NSaBjTS9IUmCIBlz3Npbu4nIGXbXLoh1s0YVEbRa6ypdYFpCI2tIzv+Dr1hlVONSVj9ly9RL5kttnJVj/BFfwrPPw6xwrKnOb9/ZPY3MQ5PHWOslgOsQQWFjLj6w8Xhc/3gROl1ih8Jf6RBtzdR/wv+JiEvwlw2E3uvHDaB0l9QhyRQFD5dyE2id+UiP7iS3tFQwNbH4p4SatwgWSSO5x6tLeQSHoh/bqYBZVKWPPQGnmUuktX/66RqVzohCJuF6caMO2nWfR6y65QJ+Bh2H4s7lMKUw9s4yJRTSGYJ6X24X6UhmtT5t0VpwlLbGkXAs+/8WNDNA8LN6PvXEJjXV5
  template:
    metadata:
      name: tinyauth-oidc
      namespace: tools
