---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-secret
  namespace: tools
spec:
  encryptedData:
    USERS: AgAuX98bmaATw9btU2ZtKpOlPhPgzQJG68ajcW8qD2Otr8jE7LQ2abdy+il/baBanlecMpWuxBN1rJ5duKLCwMwrRe1VSnz70j5KNEQkNR5f2zhXES6M17sfRXuy1h/MHf1KD6IQB4Wbutvl3+GJ8xB2CQWPtH54bP6hcGH6G7SDZLDBUAhWODYIxGFAd9zxQi6VI34Q7VYA/9xVYbnEO3MA2sHcug3Td3dfDLNxdeJkFZWg0R/RuLO7yhtNl5jssqZFO9+sklabYYaF6ppAQbzkMFPlHvqjUIKjVhxx/1ZMY2oIv54+vb1ynQ2W+NYgG6UFI7IshvcMzOzDp5OGNcEfTVEJD8XgUJNk8yqQwvuleoQOU0ZeQH4TneLzuYcKoyuy+lmqwh7/ljhe/i1CwuYJfvae2IhPxB0NoqDAakM/S9nyV/rPqwiyosaXewV+XTvrnmmKJQNzhmWiDbVGtMcSutaHsg5BApzslA6ODK7rkJEaYG+EwH8xqfHCM0LFuYDpmWdEK69j/fg8Qk1ITPF+hHUcPyyWFRLpSaBk0fddOlFIIzuqUwHf3kh9FqyNLm/2UyrvFYBrFU1/NpxBd8ACIua20T1Yw5IifCnFRlJfBnmix1cs0zjiOPriexIrUzsKZYTQooPaCNzYfxTWUvSKmWVdYuII6Hw9nDxkuasnXNeYT7szk9MeOx8je0tMVzhu9vidLQVObOWiiwExWSzXlRdtkzsh+9x/9bWcCjmSxrlurMH2eJvuGVu7EkrV7l57N5FJZdGEKmoUE9lJYIKoPnOE
  template:
    metadata:
      name: tinyauth-secret
      namespace: tools
