---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zipline-secret
  namespace: media
spec:
  encryptedData:
    CORESECRET: AgCGdQMGBkxEXQO8zOsNM6exMhRrNG2xQ5fimJeQWQ2dqwPPLQfRzLDzsf6G00qPBvHggxVx3vzqON3OtuSYKiNHPom09fD/ied5jTChNrCEMCqKtN2wDABHHAIiVbs4jeBCoFP8VQAG2zAcffac0apS6asGPMZDXjAUsbXkprKDZeA0JomyaQN+WAA7VB59gPFmbSfSgCpL5WV2S9/Y5OVvqFCxk17uztcDKdM2GTbGC71QX/Ex43t6UrMJemfH0OWUL5vtArYhnH+euo0tUomt0SaNTDPTdUjzZXsCTKCDTnSr5zFosMJnI0JB2FmofLk7obhH9UyDRmYZSS3eo3CSfl+pHYHMnAxfG0cTz0wlfb/otUjOQ5wR6HR1hclM8K8J7HOrGEppTszM6VBDwJPrBIJH6h+tAmeUwfRbrTUu4LLe2bMbMfP2OCrfTb1cB0M1mtYVmwue+CelP3JjucIdsN9WFYbOh6R9gpanSZ7MLuarXRn+AndWvcnCvuRTMSap8wJAD8TNqaYxys8O/KWFAuSMX05ltGGjTrwV8bWrluYYCHhbHV74CRsNvAkoov8Y4Qr6T2ie4V89evEPcrb1vCouBjR3e4fc8yZX2FVR5t/6NJaEKav/sb6Llx1K40pBZ1C1ZJPvTIIbTGxxjfEqz1VNMPNZ0C8J7ZfU7ZAYBLo9Kqrmtas4CARylx6LDL2n31r58vwP2nUji5Yn8tInTEc3ttTf5NwXSJEnjaAvFq3pYVgV4aZyv2nXKCYfeFTr/ijiT3bhGkMxwguLsr4P
  template:
    metadata:
      name: zipline-secret
      namespace: media
