apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-db-backup
  namespace: tools
spec:
  schedule: "0 30 3 * * *"
  backupOwnerReference: self
  cluster:
    name: n8n-db
  method: barmanObjectStore
  immediate: true
