apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media
spec:
  capacity:
    storage: 2Ti                      
  accessModes: [ReadWriteMany]         
  nfs:
    server: 192.168.3.20
    path: /volume1/media
  persistentVolumeReclaimPolicy: Retain   
  mountOptions: [nfsvers=3, nolock]