controllers:
  karakeep:
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/karakeep-app/karakeep
          tag: 0.33.2
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        env:
          MEILI_ADDR: http://karakeep-meilisearch:7700
          BROWSER_WEB_URL: http://karakeep-chrome:9222
          NEXTAUTH_URL: https://karakeep.damians.cloud
          DATA_DIR: /data # DON'T CHANGE THIS
          NEXTAUTH_SECRET:
            valueFrom:
              secretKeyRef:
                name: karakeep-secret
                key: NEXTAUTH_SECRET
          MEILI_MASTER_KEY:
            valueFrom:
              secretKeyRef:
                name: karakeep-secret
                key: MEILI_MASTER_KEY
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true

  karakeep-chrome:
    pod:
      shareProcessNamespace: true
    containers:
      app:
        image:
          repository: ghcr.io/karakeep-app/karakeep-chrome
          tag: release
        args:
          - --no-sandbox
          - --disable-gpu
          - --disable-dev-shm-usage
          - --hide-scrollbars
          - --disable-blink-features=AutomationControlled
          - --window-size=1440,900

  karakeep-meilisearch:
    containers:
      app:
        image:
          repository: getmeili/meilisearch
          tag: v1.53.1
        env:
          MEILI_NO_ANALYTICS: "true"
          MEILI_UPGRADE_DB: "true"
          MEILI_MASTER_KEY:
            valueFrom:
              secretKeyRef:
                name: karakeep-secret
                key: MEILI_MASTER_KEY

defaultPodOptions:
  labels:
    workload: selfhosted
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          workload: selfhosted
  securityContext:
    fsGroup: 1000

service:
  app:
    controller: karakeep
    ports:
      http:
        port: 3000
  chrome:
    controller: karakeep-chrome
    ports:
      http:
        port: 9222
  meilisearch:
    controller: karakeep-meilisearch
    ports:
      http:
        port: 7700

ingress:
  app:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    hosts:
      - host: karakeep.damians.cloud
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: karakeep-tls
        hosts:
          - karakeep.damians.cloud

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn
    advancedMounts:
      karakeep:
        app:
          - path: /data
  meilisearch-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: longhorn
    advancedMounts:
      karakeep-meilisearch:
        app:
          - path: /meili_data
