tinyauth:
  appUrl: https://auth.damians.cloud
  labelProvider: none
  database:
    driver: sqlite
    path: /data/tinyauth.db
  auth:
    secureCookie: true
    subdomainsEnabled: true       
    trustedProxies: 10.244.0.0/16 
    sessionExpiry: 604800
    userAttributes:
      - username: damian
        name: Damian
        email: dam.bergemann@gmail.com

  oidc:
    privateKeyPath: /data/oidc/key.pem
    publicKeyPath: /data/oidc/key.pub
    clients:
      - id: karakeep
        clientId: 7aa19782-ee5c-41eb-9cab-b184b46182a7
        clientSecretSecretRef:
          name: tinyauth-oidc
          key: KARAKEEP
        trustedRedirectUris: https://karakeep.damians.cloud/api/auth/callback/custom
        name: Karakeep
      - id: actualbudget
        clientId: b8144016-7c88-42dd-b306-15e14c74c032
        clientSecretSecretRef:
          name: tinyauth-oidc
          key: ACTUALBUDGET
        trustedRedirectUris: https://actual.damians.cloud/openid/callback
        name: Actualbudget
      - id: excalidash
        clientId: e4e4296d-29a1-42b2-b27d-c9a69770e980
        clientSecretSecretRef:
          name: tinyauth-oidc
          key: EXCALIDASH
        trustedRedirectUris: https://excalidash.damians.cloud/api/auth/oidc/callback
        name: Excalidash
      - id: memos
        clientId: 3badf65a-67ef-4d05-9348-ef5f512f6032
        clientSecretSecretRef:
          name: tinyauth-oidc
          key: MEMOS
        trustedRedirectUris: https://memos.damians.cloud/auth/callback
        name: Memos
      - id: paperless
        clientId: 26d43854-44a6-4de7-887d-3e3e3d9d0104
        clientSecretSecretRef:
          name: tinyauth-oidc
          key: PAPERLESS
        trustedRedirectUris: https://paperless.damians.cloud/accounts/oidc/tinyauth/login/callback/
        name: Paperless

  ui:
    title: damians.cloud

service:
  port: 3000

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /data

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  hosts:
    - host: auth.damians.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tinyauth-tls
      hosts:
        - auth.damians.cloud

env:
  - name: TINYAUTH_AUTH_USERS
    valueFrom:
      secretKeyRef:
        name: tinyauth-secret
        key: USERS

resources:
  requests:
    cpu: 50m
    memory: 128Mi

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: tinyauth
      namespace: tools
    spec:
      forwardAuth:
        address: http://tinyauth.tools.svc.cluster.local:3000/api/auth/traefik
        authResponseHeaders:
          - remote-user
          - remote-name
          - remote-email
          - remote-groups
          - remote-sub
          - authorization