apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.12.1
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          backupTarget: s3://longhorn-backups@garage/
          backupTargetCredentialSecret: garage-backup
        ingress:
          enabled: true
          host: longhorn.damians.cloud
          tls: true
          tlsSecret: longhorn-tls
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]     
  ignoreDifferences:                        
    - group: longhorn.io
      kind: "*"
      jsonPointers: ["/status"]
