apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-jobs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/crocofied/homelab.git
    targetRevision: main
    path: apps-manifests/longhorn-jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: longhorn.io
      kind: "*"
      jsonPointers: ["/status"]