apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.1.0
    helm:
      valuesObject:
        deployment:
          replicas: 2
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: 192.168.3.141  
        ports:
          web:
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated: { prune: true, selfHeal: true }
