apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipline
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        valueFiles:
          - $values/apps-manifests/media/zipline/values.yaml
    - repoURL: https://github.com/crocofied/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
