controllers:
  dashy:
    containers:
      app:
        image:
          repository: lissy93/dashy
          tag: 4.5.0
        env:
          NODE_ENV: production
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true

service:
  app:
    controller: dashy
    ports:
      http:
        port: 4000

ingress:
  app:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    hosts:
      - host: home.damians.cloud
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: dashy-tls
        hosts:
          - home.damians.cloud

persistence:
  config:                      
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
    globalMounts:
      - path: /app/user-data     
