controllers:
  dashy:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lissy93/dashy
          tag: 4.6.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        env:
          NODE_ENV: production
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true

defaultPodOptions:
  labels:
    workload: selfhosted
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          workload: selfhosted
  securityContext:
    fsGroup: 1000

service:
  app:
    controller: dashy
    ports:
      http:
        port: 8080

ingress:
  app:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    hosts:
      - host: home.damians.cloud
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - secretName: dashy-tls
        hosts:
          - home.damians.cloud

persistence:
  config:                      
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
    globalMounts:
      - path: /app/user-data     
